### ISSUE TITLE
What is openzwave config entry ?

### ISSUE THREAD

**Issue by yadomi** [belyalov/open-zwave-mqtt#10]
The `README.md` says that `open-zwave-mqtt` will use then "openzwave config entry" to send MQTT events.

https://github.com/belyalov/open-zwave-mqtt/blob/059cf1c8f8294ace4db9f5f686db03f6cb5875f6/README.md#L69

But where is this file and how do I create it ?

**Comment by belyalov** [comment]
@yadomi this file will be created automatically by openzwave in first run and will contain discovered devices. This is how [openzwave](https://github.com/OpenZWave/open-zwave) library works.

So just run `open-zwave-mqtt` once - and you'll get file `ozwcache_0x[homeid].xml` or `zwcfg_0x[homeid].xml`.

It looks like:
```
<?xml version="1.0" encoding="utf-8" ?>
<Driver xmlns="http://code.google.com/p/open-zwave/" version="3" home_id="0x[homeid]" node_id="1" api_capabilities="0" controller_capabilities=
        <Node id="1" name="controller" location="home" basic="2" generic="2" specific="1" type="Static PC Controller" listening="true" frequent
                <Manufacturer id="86" name="Aeotec">
                        <Product type="101" id="5a" name="ZW090 Z-Stick Gen5 US" />
                </Manufacturer>
                <CommandClasses>
                        <CommandClass id="32" name="COMMAND_CLASS_BASIC" version="1" after_mark="true">
                                <Instance index="1" />
                                <Value type="byte" genre="basic" instance="1" index="0" label="Basic" units="" read_only="false" write_only="fa
                        </CommandClass>
                </CommandClasses>
        </Node>
.....
```

**Comment by yadomi** [comment]
Thank you for your quick reply, I now better understand how OpenZwave works.

You can close the issue :)

**Comment by belyalov** [comment]
You're welcome! :)
