### ISSUE TITLE
Sending commands to zwave

### ISSUE THREAD

**Issue by jbardi** [belyalov/open-zwave-mqtt#11]
I have everything up and running, I am receiving updates to all devices through mqtt, however, I can not seem to figure out how to publish changes to zwave.  When I physically turn a binary switch On or Off, the mqtt topic correctly shows the state of 1 or 0, but is this mqtt zwave bridge read-only? Does it only show the status of devices or can I actually interact with them as well? Am I not able to publish to an MQTT topic and have it turn the switch on or off?

**Comment by jbardi** [comment]
Ok, I went through the source code of mqtt.cpp and found that I can make changes by adding /set to the end of the published topic. Could you add this information to the README file so that it makes it easier for others to know how to interact with the zwave devices over mqtt?

Thanks for this awesome project. I have been looking for weeks for a program to integrate zwave with mqtt, so I can not express how overjoyed I was to find you had already created what I was looking for.

**Comment by belyalov** [comment]
@jbardi thanks for feedback! yeah, indeed, it is not reflected in the doc, will add it soon.
👍
