### ISSUE TITLE
Duplicate message queue

### ISSUE THREAD

**Issue by jgaret** [belyalov/open-zwave-mqtt#13]
Hello,

When receiving a message from a node, open-zwave-mqtt sends 2 messages to the mqtt broker.
One with the zwave mapping, one without (with command class and instance number).
For example :
> 2019-04-02 21:44:10.016 Info, Node024, Received SensorMultiLevel report from node 24, instance 1, Temperature: value=21.7C
> 2019-04-02 21:44:10.018 Info, MQTT PUBLISH: ozw2mqtt/Rez de Chaussée/Détecteur Salon Cuisine/sensor_multilevel/temperature -> 21.7
> 2019-04-02 21:44:10.019 Info, MQTT PUBLISH: ozw2mqtt/24/49/1 -> 21.7

Have I missed something in the configuration or command line ?

**Comment by jgaret** [comment]
Ok, found in the doc... --mqtt-no-id-topics ! I did not read enough.

Sorry for inconvenience.

**Comment by belyalov** [comment]
NP, FYI, there is another useful feature - **topic maps**, e.g.
```
home/master/wall_lights/switch_multilevel/1/level  = home/master/wall_lights
```

P.S. if you like this project - star it :)
